name: Build and push Docker image
on:
  push:
    branches:
      - main

env:
  REGISTRY: 889624388708.dkr.ecr.eu-central-1.amazonaws.com
  USER: AWS
  REPO: transcript
  TAG: test
  REGION: eu-central-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Docker cache and images
        run: |
          docker system prune --all --force --volumes

      - name: Remove unnecessary tools
        run: |
          sudo apt-get remove --purge -y azure-cli google-cloud-sdk firefox
          sudo apt-get autoremove -y

      - name: Cleanup temporary files
        run: sudo rm -rf /tmp/*

      - name: Stop and disable unused services
        run: |
          sudo systemctl stop mysql
          sudo systemctl stop postgresql
          sudo systemctl disable mysql
          sudo systemctl disable postgresql

      - name: Check disk space
        run: df -h

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up environment variables
        run: echo "TAG=$(date +'%d.%m.%y')" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Log into registry ${{ env.REGISTRY }}
        run: aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.REGISTRY }}

      - name: Build and push Docker image
        run: |
          docker build \
            --progress=plain \
            --build-arg HUGGING_FACE_HUB_WRITE_TOKEN=${{ secrets.HUGGING_FACE_HUB_WRITE_TOKEN }} \
            -t ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.TAG }} . --build-arg PROD_DB_URL=${{vars.PROD_DB_URL}} 
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.TAG }}
